DROP DATABASE IF EXISTS company_DB;
CREATE database company_DB;

USE company_DB;

CREATE TABLE employee (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT FOREIGN KEY,
manager_id INT FOREIGN KEY NULL
);

CREATE TABLE role (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
title VARCHAR(30),
salary DECIMAL,
department_id INT FOREIGN KEY
);

CREATE TABLE department (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(30)
);